api_version: "1"

databricks:
  serving_endpoint:
    - name: "databricks-meta-llama-3-3-70b-instruct"   # LLM endpoint
    - name: "databricks-bge-large-en"                   # Embedding endpoint

  vector_search_index:
    - name: "catalog.schema.sephora_index"

  # optional — only if agent uses UC functions as tools
  function:
    - name: "catalog.schema.my_tool_function"